### ISSUE TITLE
Add parallel git clone / fetch support

### ISSUE THREAD

**Issue by countzero** [countzero/backup_github_repositories#1]
### User story

As a user I want to execute the git clone and fetch operations in parallel so that I can rapidly backup many GitHub repositories.

### Acceptance criteria

- [x] The script has a `-maxConcurrency` flag that defaults to 8
- [x] The result of a completed backup operation is logged to the console as fast as possible

### Description

PowerShell has background jobs to parallelize the execution of long running jobs. Currently the backup script processing is serial. 

The assumption is, that the total backup speed can be increased by parallelizing the execution of the git clone and fetch operations.

### Implementation steps

- [x] Create a proof of concept
- [x] Add `-maxConcurrency` flag
- [x] Add background job execution handling
- [x] Add documentation

### Additional context

**Proof of concept**
1. [parallel_jobs.ps1](https://gist.github.com/countzero/ef6c801456146664cf9da120cfec56cd)
2. [parallel_jobs_max_concurrency_wait_strategy.ps1](https://gist.github.com/countzero/87ef1a5e187c7479972576f6a282e8d3)
3. [parallel_jobs_max_concurrency_while_strategy.ps1](https://gist.github.com/countzero/ca1fc4cbecc1676aa7e4d2433a8cdce1)

**Comment by countzero** [comment]
Implemented in v1.1.0
